#!/usr/bin/env bash

set -euo pipefail

declare -ar TARGETS=(
    x86_64-linux-musl
    x86_64-macos-none
    aarch64-linux-musl
    aarch64-macos-none
)

export SCALANATIVE_MODE="release-full"; # {debug, release-fast, release-full}
export SCALANATIVE_LTO="thin"; # {none, full, thin}

sbt -client 'project scalalsNative'
sbt -client 'ninjaCompile'

for target in "${TARGETS[@]}"; do
    echo "BUILD - $target"
    sbt -client "set targetTriplet := Some(\"$target\")"
    sbt -client "ninja"
    ninja -f native/target/scala-3.3.1/native/build.ninja
    echo
done

mv -v native/target/scala-3.3.1/scalals-* .


