conditions: v1

if: branch = master OR tag IS present

os:
  - linux

language: scala

scala:
  - 2.11.12

install:
  - (cd modules/scala-native && sbt -Dfile.encoding=UTF8 ^^1.2.8 rebuild)
  - (cd modules/scopt && sbt -Dfile.encoding=UTF8 -sbt-version 1.2.8 ++$TRAVIS_SCALA_VERSION scoptNative/publishLocal)

script:
  - sbt -Dfile.encoding=UTF8 ++$TRAVIS_SCALA_VERSION scalalsNative/run

sudo: false

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
