name: Update niv

on:
  workflow_dispatch:
  schedule:
    # every tuesday at 3pm UTC
    - cron: '0 15 * * tue'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: cbley
        extraPullNames: pre-commit-hooks
    - run: nix-shell --run "niv update"
    - run: nix-shell --run "pre-commit run --all-files" || true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.11.0
      with:
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
        token: "${{ secrets.PR_TOKEN }}"
