name: Update flake ❄

on:
  workflow_dispatch:
  schedule:
    # every wednesday at 3pm UTC
    - cron: '0 15 * * wed'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
    - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: cbley
        extraPullNames: pre-commit-hooks
    - name: Set author identity
      run: |
        git config user.email '${{ github.actor }}@users.noreply.github.com'
        git config user.name '${{ github.actor }}'
    - run: nix flake update --commit-lock-file
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        commit-message: "[automation] flake update"
        title: "[automation] flake update"
        branch: "automation/update-flake-inputs"
        labels: "dependencies"
        token: "${{ secrets.PR_TOKEN }}"
    - name: Enable Pull Request Automerge
      run: gh pr merge --rebase --auto "${{ steps.create-pr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.PR_TOKEN }}
