name: Update niv

on:
  schedule:
    # every day at 8am UTC
    - cron: '0 8 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    # https://github.com/nmattia/niv/issues/280
    - run: GITHUB_PATH= nix-shell --run "niv update"
    - run: nix-shell --run "pre-commit run --all-files" || true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
